### ISSUE TITLE
TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by ryangallen** [jpulec/django-protractor#6]
Currently getting a traceback when test runs via `python manage.py protractor`:

```
Starting webdriver...
Creating test database for alias 'default'...
Starting server...
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/me/.virtualenvs/sdj/lib/python3.4/site-packages/protractor/management/commands/protractor.py", line 111, in runserver
    stdout=open(os.devnull, 'wb')
  File "/Users/me/.virtualenvs/sdj/lib/python3.4/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/Users/me/.virtualenvs/sdj/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 49, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/me/.virtualenvs/sdj/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/me/.virtualenvs/sdj/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 88, in handle
    self.run(**options)
  File "/Users/me/.virtualenvs/sdj/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 99, in run
    self.inner_run(None, **options)
  File "/Users/me/.virtualenvs/sdj/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    self.stdout.write("Performing system checks...\n\n")
  File "/Users/me/.virtualenvs/sdj/lib/python3.4/site-packages/django/core/management/base.py", line 114, in write
    self._out.write(force_str(style_func(msg)))
TypeError: 'str' does not support the buffer interface
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
........

Finished in 23.377 seconds
8 tests, 11 assertions, 0 failures
```

**Comment by jpulec** [comment]
I just pushed a change to master that should deal with that python 3 issue. Let me know if that works.

**Comment by ryangallen** [comment]
Different issue now:

```
Starting webdriver...
Creating test database for alias 'default'...
Starting server...
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at [object Object].Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:416:22)
    at [object Object].DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/usr/local/lib/node_modules/protractor/lib/runner.js:180:37)
    at /usr/local/lib/node_modules/protractor/lib/runner.js:268:21
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:573:44
[launcher] Process exited with error code 1
Destroying test database for alias 'default'...
Failed
```

Sorry to bring these issues to the table without a fix, still trying to learn node/protractor..
